# -*- coding: utf-8 -*-
"""datafortraining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1VQ7yJz4JgvYjWFQ3CojHDkwAGn_84t
"""

def modeldata(
    database,
    splittingfile
):

  import schnetpack as spk
  import schnetpack.transform as trn

  np.random.seed(29)

  custom_data_one = spk.data.AtomsDataModule(
    f'./{database}',
    batch_size=16,
    distance_unit='Ang',
    property_units={},
    num_train=int(data*0.8),
    num_val=int(data*0.1),
    num_test=int(data*0.1),
    transforms=[
        trn.ASENeighborList(cutoff=5.),
        trn.CastTo32()
    ],
    num_workers=1,
    split_file=os.path.join(fockmatrixtutone, f"{splittingfile}"),
    pin_memory=True,
    load_properties=['fock_matrix']
  )
  custom_data_one.prepare_data()
  custom_data_one.setup()
  print(type(custom_data_one))
  return custom_data_one