# -*- coding: utf-8 -*-
"""define_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wAU-CO9CdU9v1CfMfEEqeSug0oWOMLaB
"""

def task_define(initial_lr, lr_factor, lr_patience, lr_threshold):
  initial_lr = 1e-4
  lr_factor = 0.8
  lr_patience = 3
  lr_threshold = 1e-3
  task = AtomisticTask(
    model=nnpot,
    outputs=[output_fock],
    optimizer_cls=torch.optim.Adam,
    optimizer_args={"lr": initial_lr},
    scheduler_cls=torch.optim.lr_scheduler.ReduceLROnPlateau,
    scheduler_args={"threshold":lr_threshold,"patience": lr_patience, "factor":lr_factor},
    scheduler_monitor="val_loss"
  )