# -*- coding: utf-8 -*-
"""modeltraining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sPYon_cXIJy3YcmjcZkTAL1ePkPlZmG
"""

def training(custom_data_one, modelname, version):
  logger = pl.loggers.TensorBoardLogger(save_dir=fockmatrixtutone,name=f'{version}')
  callbacks = [
    spk.train.ModelCheckpoint(
        model_path=os.path.join(fockmatrixtutone, f"{modelname}"),
        save_top_k=1,
        monitor="val_loss"
    ),
    pl.callbacks.EarlyStopping(
        monitor="val_loss",
        min_delta=1e-6,
        patience=10,
        verbose=False,
        mode="min"
    )
  ]

  trainer = pl.Trainer(
    callbacks=callbacks,
    logger=logger,
    default_root_dir=fockmatrixtutone,
    max_epochs=100, # for testing, we restrict the number of epochs
  )

  trainer.fit(task, datamodule=custom_data_one)