# -*- coding: utf-8 -*-
"""model_loss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvfN0LYxxx2d5FKKfIaPgM8ioUwZODRh
"""

def custom_loss(pred, targets, mdimension,batch_size):
  pred = torch.reshape(pred, (-1, mdimension, mdimension))
  targets = torch.reshape(targets, (-1, mdimension, mdimension))

  loss = 0
  for i in range(pred.shape[0]):
        squared_diff = torch.square(targets[i] - pred[i])
        # Sum the squared differences and normalize by the number of elements
        loss += torch.sum(squared_diff) / (mdimension * mdimension)
  return loss/pred.shape[0]