# -*- coding: utf-8 -*-
"""model_prequisites.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQhuiSaeB6cP-kzqCxPZzDqK-Itk16Gd
"""

def model_prereqs():
  splitfiles = ['splittingfold1.npz', 'splittingfold2.npz', 'splittingfold3.npz', 'splittingfold4.npz', 'splittingfold5.npz']
  import os
  import random
  import numpy as np
  import torch
  seed = 29
  os.environ['PYTHONHASHSEED'] = str(seed)
  random.seed(seed)
  np.random.seed(seed)
  torch.manual_seed(seed)
  torch.cuda.manual_seed(seed)
  torch.backends.cudnn.deterministic = True

  fockmatrixtutone = './fockmatrixtutone'
  if not os.path.exists('fockmatrixtutone'):
    os.makedirs(fockmatrixtutone)

  directory_path = './fockmatrixtutone'
  import shutil
  for file_name in splitfiles:
    shutil.move(file_name, os.path.join(directory_path, file_name))

  print(f"Files have been moved to {directory_path}")
  return fockmatrixtutone