# -*- coding: utf-8 -*-
"""calculate_c_matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwgbwXy6jWucdJvoQDq77wJin9mD5DId
"""

def getC(result, S, num):
  from scipy.linalg import eigh
  import numpy as np
  Cmatrices = []
  for i in range(num):
    eigenvalues, C = eigh(result[i].reshape(32,32), S[i].reshape(32,32))
    Cmatrices.append(C)
  return np.array(Cmatrices)