# -*- coding: utf-8 -*-
"""retrieve_s_matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmE6pJae1MUA9tGTw28sJEw-Do2JVjXC
"""

def retrieveSmatrix(index, upper):
  import numpy as np
  np.load('overlap_matrices_open.npy')
  array = []
  for i in index[0:upper]:
    S = np.load('overlap_matrices_open.npy')[i]
    array.append(S)
  return array