# -*- coding: utf-8 -*-
"""cmatrix phase correction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcfKP2k0YloRbwUGnTgTinao_udTk7Ex
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
def phase_correct(file, matrixdimension):
  #Load the file pre-correction
  correction = np.load(file)
  #Assign reference for phase correction
  reference = correction[0]
  #Phase correct
  for i in range(1,1000):
    for j in range(105):
      matrix = correction[i][j]
      if np.dot(reference[j], matrix) < 0:
        correction[i][j] = correction[i][j]*-1
  np.save('phase_corrected.npy', correction)