# -*- coding: utf-8 -*-
"""write_5fold_splitting_files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txbWhuiBtsePgo7eD5Jkl4i2IgBS8LXN
"""

def make_5_fold_split_files(datasize):

  import numpy as np

  onerange = np.arange(datasize)
  splot = len(onerange)

  trainfold1 = onerange[:int(splot*0.8)]
  valfold1 = onerange[int(splot*0.8):int(splot*0.9)]
  testfold1 = onerange[int(splot*0.9):int(splot)]

  stacking1 = onerange[:int(splot*0.6)]
  stacking2 = onerange[int(splot*0.8):int(splot)]
  trainfold2 = np.concatenate((stacking1,stacking2))
  valfold2 = onerange[int(splot*0.6):int(splot*0.7)]
  testfold2 = onerange[int(splot*0.7):int(splot*0.8)]

  stacking3 = onerange[:int(splot*0.4)]
  stacking4 = onerange[int(splot*0.6):int(splot)]
  trainfold3 = np.concatenate((stacking3,stacking4))
  valfold3 = onerange[int(splot*0.4):int(splot*0.5)]
  testfold3 = onerange[int(splot*0.5):int(splot*0.6)]

  stacking5 = onerange[:int(splot*0.2)]
  stacking6 = onerange[int(splot*0.4):int(splot)]
  trainfold4 = np.concatenate((stacking5,stacking6))
  valfold4 = onerange[int(splot*0.2):int(splot*0.3)]
  testfold4 = onerange[int(splot*0.3):int(splot*0.4)]

  trainfold5 = onerange[int(splot*0.2):int(splot)]
  valfold5 = onerange[int(splot*0):int(splot*0.1)]
  testfold5 = onerange[int(splot*0.1):int(splot*0.2)]

  splitfold1 = {'train_idx': trainfold1,
                'val_idx': valfold1,
                'test_idx': testfold1}

  splitfold2 = {'train_idx': trainfold2,
                'val_idx': valfold2,
                'test_idx': testfold2}

  splitfold3 = {'train_idx': trainfold3,
                'val_idx': valfold3,
                'test_idx': testfold3}

  splitfold4 = {'train_idx': trainfold4,
                'val_idx': valfold4,
                'test_idx': testfold4}

  splitfold5 = {'train_idx': trainfold5,
                'val_idx': valfold5,
                'test_idx': testfold5}

  np.savez('splittingfold1.npz', train_idx=splitfold1['train_idx'], val_idx=splitfold1['val_idx'], test_idx=splitfold1['test_idx'])
  np.savez('splittingfold2.npz', train_idx=splitfold2['train_idx'], val_idx=splitfold2['val_idx'], test_idx=splitfold2['test_idx'])
  np.savez('splittingfold3.npz', train_idx=splitfold3['train_idx'], val_idx=splitfold3['val_idx'], test_idx=splitfold3['test_idx'])
  np.savez('splittingfold4.npz', train_idx=splitfold4['train_idx'], val_idx=splitfold4['val_idx'], test_idx=splitfold4['test_idx'])
  np.savez('splittingfold5.npz', train_idx=splitfold5['train_idx'], val_idx=splitfold5['val_idx'], test_idx=splitfold5['test_idx'])
