# -*- coding: utf-8 -*-
"""get_overlap_matrices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SAAbHd7t-Gsp5Sx8UvgUYfcu7xYp4J6V
"""

import h5py

def overlapmatrixget(ranges, matrixdimension):
  overlap_matrices = []
  for i in range(ranges):
    filename = 'Z:\\electrocyclic\\open\\open_g2m05_' + str(i).zfill(4) + '\\MB\\open_g2m05_' + \
    str(i).zfill(4) + '_MB.rasscf.h5'
    file_h5 = h5py.File(filename,'r')
    matrix = file_h5['AO_OVERLAP_MATRIX'][()].reshape(matrixdimension, matrixdimension)
    overlap_matrices.append(np.array(matrix))
    file_h5.close()
  np.save('overlap_matrices_open.npy', overlap_matrices)
  return overlap_matrices