# -*- coding: utf-8 -*-
"""get_orbitalcoefficients.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Zxn6D8NmMrK1Y_0lEvqkE2QVMl68Yjj
"""

import h5py

def orbcoefget(ranges):
  orbcofe = []
  for i in range(ranges):
    file_ras_name = 'Z:\\electrocyclic\\open\\open_g2m05_' + str(i).zfill(4) + '\\MB\\open_g2m05_' + \
    str(i).zfill(4) + '_MB.RasOrb'
    matrix_cof = read_orbcoef(file_ras_name)
    orbcofe.append(np.array(matrix_cof))
  np.save('orbcof_open.npy',orbcofe)