# -*- coding: utf-8 -*-
"""get_energy_matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAWXny-dSm7NDGfL9_z9EL441KnOFC-7
"""

import h5py

def getenergymatrix(ranges):
  nrgs = []
  for i in range(ranges):
    file_ras_name = 'Z:\\electrocyclic\\open\\open_g2m05_' + str(i).zfill(4) + '\\MB\\open_g2m05_' + \
    str(i).zfill(4) + '_MB.RasOrb'
    matrix_nrg = (np.diag(read_nrg(file_ras_name)))
    nrgs.append(np.array(matrix_nrg))
  np.save('nrg_matrix_open.npy', nrgs)
  return nrgs