# -*- coding: utf-8 -*-
"""get_event_files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11g4FWe-88fUUJRmEt95ZKs3igWnKUPkx
"""

import os
import numpy as np

def get_event_files(director, filename, parameters):
  run_dirs = [director]
  eventfiles = []
  # List the files in the run directory to identify the event file
  files_in_run_dir = {}
  for i, directory in enumerate(run_dirs, start=1):
    files_in_run_dir[i] = os.listdir(directory)
    for file in files_in_run_dir[i]:
      if file.startswith("events.out.tfevents"):
        eventfiles.append(file)
        print(file)
  from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
  for run_dir, event in zip(run_dirs, eventfiles):
    event_acc = EventAccumulator(os.path.join(run_dir, event))
    event_acc.Reload()
    print(event_acc.Tags())

  val_events = []

  for run_dir, event in zip(run_dirs, eventfiles):
    event_acc = EventAccumulator(os.path.join(run_dir, event))
    event_acc.Reload()
    val_loss_events = event_acc.Scalars('val_loss')
    validation_losses = [event.value for event in val_loss_events]
    val_events.append(validation_losses)


  train_events = []

  for run_dir, event in zip(run_dirs, eventfiles):
    event_acc = EventAccumulator(os.path.join(run_dir, event))
    event_acc.Reload()
    train_loss_events = event_acc.Scalars('train_loss')
    train_losses = [event.value for event in train_loss_events]
    train_events.append(train_losses)
  validation_arrays = np.array(val_events)
  train_arrays = np.array(train_events)
  np.savez(filename + '.npz',validation_arrays=validation_arrays,train_arrays=train_arrays,parameters=parameters)
  print(filename + '.npz')
