# -*- coding: utf-8 -*-
"""get_actual_matrices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uWS8JDZw2bFPzLYjF8tejeWmL1ugq48
"""

def retrieveactual(actual, num):
  import numpy as np
  array = []
  for i in range(num):
    actually = np.array(np.load(actual, allow_pickle=True)[i]['fock_matrix'])
    array.append(actually)
  return np.array(array)