# -*- coding: utf-8 -*-
"""test_loss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zv143mtmR7xtSdZ4zmVmEumVUi0aGVDl
"""

def custom_test_loss(pred, targets, mdimension):
  pred = np.reshape(pred, (-1, mdimension, mdimension))
  targets = np.reshape(targets, (-1, mdimension, mdimension))

  loss = 0
  for i in range(pred.shape[0]):
        squared_diff = np.square(targets[i] - pred[i])
        # Sum the squared differences and normalize by the number of elements
        loss += np.sum(squared_diff) / (mdimension * mdimension)
  return loss/pred.shape[0]