# -*- coding: utf-8 -*-
"""calculate_fock_matrices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epdLx37PuXD7dzkK_5rdiJJy6oPx_5uU
"""

def getfockmatrices(overlap_matrix, nrgmat, orbcoeff, ranges):
  Fock = []
  for i in range(ranges):
    S = overlap_matrix[i]
    e = nrgmat[i]
    C = orbcoeff[i]
    C = C.T
    C1 = np.linalg.inv(C)
    F = S@C@e@C1
    Fock.append(np.array(F))
  np.save('fockmatrices_fixed.npy', Fock)